# CMake generated Testfile for 
# Source directory: /home/dogi/openwrt/trunk/build_dir/host/cmake-2.8.11.2/Tests/RunCMake
# Build directory: /home/dogi/openwrt/trunk/build_dir/host/cmake-2.8.11.2/Tests/RunCMake
# 
# This file includes the relevent testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
ADD_TEST(RunCMake.CMP0019 "/home/dogi/openwrt/trunk/build_dir/host/cmake-2.8.11.2/bin/cmake" "-DCMAKE_MODULE_PATH=/home/dogi/openwrt/trunk/build_dir/host/cmake-2.8.11.2/Tests/RunCMake" "-DRunCMake_GENERATOR=Unix Makefiles" "-DRunCMake_GENERATOR_TOOLSET=" "-DRunCMake_SOURCE_DIR=/home/dogi/openwrt/trunk/build_dir/host/cmake-2.8.11.2/Tests/RunCMake/CMP0019" "-DRunCMake_BINARY_DIR=/home/dogi/openwrt/trunk/build_dir/host/cmake-2.8.11.2/Tests/RunCMake/CMP0019" "-P" "/home/dogi/openwrt/trunk/build_dir/host/cmake-2.8.11.2/Tests/RunCMake/CMP0019/RunCMakeTest.cmake")
ADD_TEST(RunCMake.CTest "/home/dogi/openwrt/trunk/build_dir/host/cmake-2.8.11.2/bin/cmake" "-DCMAKE_MODULE_PATH=/home/dogi/openwrt/trunk/build_dir/host/cmake-2.8.11.2/Tests/RunCMake" "-DRunCMake_GENERATOR=Unix Makefiles" "-DRunCMake_GENERATOR_TOOLSET=" "-DRunCMake_SOURCE_DIR=/home/dogi/openwrt/trunk/build_dir/host/cmake-2.8.11.2/Tests/RunCMake/CTest" "-DRunCMake_BINARY_DIR=/home/dogi/openwrt/trunk/build_dir/host/cmake-2.8.11.2/Tests/RunCMake/CTest" "-P" "/home/dogi/openwrt/trunk/build_dir/host/cmake-2.8.11.2/Tests/RunCMake/CTest/RunCMakeTest.cmake")
ADD_TEST(RunCMake.CompilerChange "/home/dogi/openwrt/trunk/build_dir/host/cmake-2.8.11.2/bin/cmake" "-DCMAKE_MODULE_PATH=/home/dogi/openwrt/trunk/build_dir/host/cmake-2.8.11.2/Tests/RunCMake" "-DRunCMake_GENERATOR=Unix Makefiles" "-DRunCMake_GENERATOR_TOOLSET=" "-DRunCMake_SOURCE_DIR=/home/dogi/openwrt/trunk/build_dir/host/cmake-2.8.11.2/Tests/RunCMake/CompilerChange" "-DRunCMake_BINARY_DIR=/home/dogi/openwrt/trunk/build_dir/host/cmake-2.8.11.2/Tests/RunCMake/CompilerChange" "-P" "/home/dogi/openwrt/trunk/build_dir/host/cmake-2.8.11.2/Tests/RunCMake/CompilerChange/RunCMakeTest.cmake")
ADD_TEST(RunCMake.ExternalData "/home/dogi/openwrt/trunk/build_dir/host/cmake-2.8.11.2/bin/cmake" "-DCMAKE_MODULE_PATH=/home/dogi/openwrt/trunk/build_dir/host/cmake-2.8.11.2/Tests/RunCMake" "-DRunCMake_GENERATOR=Unix Makefiles" "-DRunCMake_GENERATOR_TOOLSET=" "-DRunCMake_SOURCE_DIR=/home/dogi/openwrt/trunk/build_dir/host/cmake-2.8.11.2/Tests/RunCMake/ExternalData" "-DRunCMake_BINARY_DIR=/home/dogi/openwrt/trunk/build_dir/host/cmake-2.8.11.2/Tests/RunCMake/ExternalData" "-P" "/home/dogi/openwrt/trunk/build_dir/host/cmake-2.8.11.2/Tests/RunCMake/ExternalData/RunCMakeTest.cmake")
ADD_TEST(RunCMake.FPHSA "/home/dogi/openwrt/trunk/build_dir/host/cmake-2.8.11.2/bin/cmake" "-DCMAKE_MODULE_PATH=/home/dogi/openwrt/trunk/build_dir/host/cmake-2.8.11.2/Tests/RunCMake" "-DRunCMake_GENERATOR=Unix Makefiles" "-DRunCMake_GENERATOR_TOOLSET=" "-DRunCMake_SOURCE_DIR=/home/dogi/openwrt/trunk/build_dir/host/cmake-2.8.11.2/Tests/RunCMake/FPHSA" "-DRunCMake_BINARY_DIR=/home/dogi/openwrt/trunk/build_dir/host/cmake-2.8.11.2/Tests/RunCMake/FPHSA" "-P" "/home/dogi/openwrt/trunk/build_dir/host/cmake-2.8.11.2/Tests/RunCMake/FPHSA/RunCMakeTest.cmake")
ADD_TEST(RunCMake.GeneratorExpression "/home/dogi/openwrt/trunk/build_dir/host/cmake-2.8.11.2/bin/cmake" "-DCMAKE_MODULE_PATH=/home/dogi/openwrt/trunk/build_dir/host/cmake-2.8.11.2/Tests/RunCMake" "-DRunCMake_GENERATOR=Unix Makefiles" "-DRunCMake_GENERATOR_TOOLSET=" "-DRunCMake_SOURCE_DIR=/home/dogi/openwrt/trunk/build_dir/host/cmake-2.8.11.2/Tests/RunCMake/GeneratorExpression" "-DRunCMake_BINARY_DIR=/home/dogi/openwrt/trunk/build_dir/host/cmake-2.8.11.2/Tests/RunCMake/GeneratorExpression" "-P" "/home/dogi/openwrt/trunk/build_dir/host/cmake-2.8.11.2/Tests/RunCMake/GeneratorExpression/RunCMakeTest.cmake")
ADD_TEST(RunCMake.GeneratorToolset "/home/dogi/openwrt/trunk/build_dir/host/cmake-2.8.11.2/bin/cmake" "-DCMAKE_MODULE_PATH=/home/dogi/openwrt/trunk/build_dir/host/cmake-2.8.11.2/Tests/RunCMake" "-DRunCMake_GENERATOR=Unix Makefiles" "-DRunCMake_GENERATOR_TOOLSET=" "-DRunCMake_SOURCE_DIR=/home/dogi/openwrt/trunk/build_dir/host/cmake-2.8.11.2/Tests/RunCMake/GeneratorToolset" "-DRunCMake_BINARY_DIR=/home/dogi/openwrt/trunk/build_dir/host/cmake-2.8.11.2/Tests/RunCMake/GeneratorToolset" "-P" "/home/dogi/openwrt/trunk/build_dir/host/cmake-2.8.11.2/Tests/RunCMake/GeneratorToolset/RunCMakeTest.cmake")
ADD_TEST(RunCMake.TargetPropertyGeneratorExpressions "/home/dogi/openwrt/trunk/build_dir/host/cmake-2.8.11.2/bin/cmake" "-DCMAKE_MODULE_PATH=/home/dogi/openwrt/trunk/build_dir/host/cmake-2.8.11.2/Tests/RunCMake" "-DRunCMake_GENERATOR=Unix Makefiles" "-DRunCMake_GENERATOR_TOOLSET=" "-DRunCMake_SOURCE_DIR=/home/dogi/openwrt/trunk/build_dir/host/cmake-2.8.11.2/Tests/RunCMake/TargetPropertyGeneratorExpressions" "-DRunCMake_BINARY_DIR=/home/dogi/openwrt/trunk/build_dir/host/cmake-2.8.11.2/Tests/RunCMake/TargetPropertyGeneratorExpressions" "-P" "/home/dogi/openwrt/trunk/build_dir/host/cmake-2.8.11.2/Tests/RunCMake/TargetPropertyGeneratorExpressions/RunCMakeTest.cmake")
ADD_TEST(RunCMake.Languages "/home/dogi/openwrt/trunk/build_dir/host/cmake-2.8.11.2/bin/cmake" "-DCMAKE_MODULE_PATH=/home/dogi/openwrt/trunk/build_dir/host/cmake-2.8.11.2/Tests/RunCMake" "-DRunCMake_GENERATOR=Unix Makefiles" "-DRunCMake_GENERATOR_TOOLSET=" "-DRunCMake_SOURCE_DIR=/home/dogi/openwrt/trunk/build_dir/host/cmake-2.8.11.2/Tests/RunCMake/Languages" "-DRunCMake_BINARY_DIR=/home/dogi/openwrt/trunk/build_dir/host/cmake-2.8.11.2/Tests/RunCMake/Languages" "-P" "/home/dogi/openwrt/trunk/build_dir/host/cmake-2.8.11.2/Tests/RunCMake/Languages/RunCMakeTest.cmake")
ADD_TEST(RunCMake.ObjectLibrary "/home/dogi/openwrt/trunk/build_dir/host/cmake-2.8.11.2/bin/cmake" "-DCMAKE_MODULE_PATH=/home/dogi/openwrt/trunk/build_dir/host/cmake-2.8.11.2/Tests/RunCMake" "-DRunCMake_GENERATOR=Unix Makefiles" "-DRunCMake_GENERATOR_TOOLSET=" "-DRunCMake_SOURCE_DIR=/home/dogi/openwrt/trunk/build_dir/host/cmake-2.8.11.2/Tests/RunCMake/ObjectLibrary" "-DRunCMake_BINARY_DIR=/home/dogi/openwrt/trunk/build_dir/host/cmake-2.8.11.2/Tests/RunCMake/ObjectLibrary" "-P" "/home/dogi/openwrt/trunk/build_dir/host/cmake-2.8.11.2/Tests/RunCMake/ObjectLibrary/RunCMakeTest.cmake")
ADD_TEST(RunCMake.PositionIndependentCode "/home/dogi/openwrt/trunk/build_dir/host/cmake-2.8.11.2/bin/cmake" "-DCMAKE_MODULE_PATH=/home/dogi/openwrt/trunk/build_dir/host/cmake-2.8.11.2/Tests/RunCMake" "-DRunCMake_GENERATOR=Unix Makefiles" "-DRunCMake_GENERATOR_TOOLSET=" "-DRunCMake_SOURCE_DIR=/home/dogi/openwrt/trunk/build_dir/host/cmake-2.8.11.2/Tests/RunCMake/PositionIndependentCode" "-DRunCMake_BINARY_DIR=/home/dogi/openwrt/trunk/build_dir/host/cmake-2.8.11.2/Tests/RunCMake/PositionIndependentCode" "-P" "/home/dogi/openwrt/trunk/build_dir/host/cmake-2.8.11.2/Tests/RunCMake/PositionIndependentCode/RunCMakeTest.cmake")
ADD_TEST(RunCMake.CompatibleInterface "/home/dogi/openwrt/trunk/build_dir/host/cmake-2.8.11.2/bin/cmake" "-DCMAKE_MODULE_PATH=/home/dogi/openwrt/trunk/build_dir/host/cmake-2.8.11.2/Tests/RunCMake" "-DRunCMake_GENERATOR=Unix Makefiles" "-DRunCMake_GENERATOR_TOOLSET=" "-DRunCMake_SOURCE_DIR=/home/dogi/openwrt/trunk/build_dir/host/cmake-2.8.11.2/Tests/RunCMake/CompatibleInterface" "-DRunCMake_BINARY_DIR=/home/dogi/openwrt/trunk/build_dir/host/cmake-2.8.11.2/Tests/RunCMake/CompatibleInterface" "-P" "/home/dogi/openwrt/trunk/build_dir/host/cmake-2.8.11.2/Tests/RunCMake/CompatibleInterface/RunCMakeTest.cmake")
ADD_TEST(RunCMake.add_dependencies "/home/dogi/openwrt/trunk/build_dir/host/cmake-2.8.11.2/bin/cmake" "-DCMAKE_MODULE_PATH=/home/dogi/openwrt/trunk/build_dir/host/cmake-2.8.11.2/Tests/RunCMake" "-DRunCMake_GENERATOR=Unix Makefiles" "-DRunCMake_GENERATOR_TOOLSET=" "-DRunCMake_SOURCE_DIR=/home/dogi/openwrt/trunk/build_dir/host/cmake-2.8.11.2/Tests/RunCMake/add_dependencies" "-DRunCMake_BINARY_DIR=/home/dogi/openwrt/trunk/build_dir/host/cmake-2.8.11.2/Tests/RunCMake/add_dependencies" "-P" "/home/dogi/openwrt/trunk/build_dir/host/cmake-2.8.11.2/Tests/RunCMake/add_dependencies/RunCMakeTest.cmake")
ADD_TEST(RunCMake.build_command "/home/dogi/openwrt/trunk/build_dir/host/cmake-2.8.11.2/bin/cmake" "-DCMAKE_MODULE_PATH=/home/dogi/openwrt/trunk/build_dir/host/cmake-2.8.11.2/Tests/RunCMake" "-DRunCMake_GENERATOR=Unix Makefiles" "-DRunCMake_GENERATOR_TOOLSET=" "-DRunCMake_SOURCE_DIR=/home/dogi/openwrt/trunk/build_dir/host/cmake-2.8.11.2/Tests/RunCMake/build_command" "-DRunCMake_BINARY_DIR=/home/dogi/openwrt/trunk/build_dir/host/cmake-2.8.11.2/Tests/RunCMake/build_command" "-P" "/home/dogi/openwrt/trunk/build_dir/host/cmake-2.8.11.2/Tests/RunCMake/build_command/RunCMakeTest.cmake")
ADD_TEST(RunCMake.find_package "/home/dogi/openwrt/trunk/build_dir/host/cmake-2.8.11.2/bin/cmake" "-DCMAKE_MODULE_PATH=/home/dogi/openwrt/trunk/build_dir/host/cmake-2.8.11.2/Tests/RunCMake" "-DRunCMake_GENERATOR=Unix Makefiles" "-DRunCMake_GENERATOR_TOOLSET=" "-DRunCMake_SOURCE_DIR=/home/dogi/openwrt/trunk/build_dir/host/cmake-2.8.11.2/Tests/RunCMake/find_package" "-DRunCMake_BINARY_DIR=/home/dogi/openwrt/trunk/build_dir/host/cmake-2.8.11.2/Tests/RunCMake/find_package" "-P" "/home/dogi/openwrt/trunk/build_dir/host/cmake-2.8.11.2/Tests/RunCMake/find_package/RunCMakeTest.cmake")
ADD_TEST(RunCMake.include "/home/dogi/openwrt/trunk/build_dir/host/cmake-2.8.11.2/bin/cmake" "-DCMAKE_MODULE_PATH=/home/dogi/openwrt/trunk/build_dir/host/cmake-2.8.11.2/Tests/RunCMake" "-DRunCMake_GENERATOR=Unix Makefiles" "-DRunCMake_GENERATOR_TOOLSET=" "-DRunCMake_SOURCE_DIR=/home/dogi/openwrt/trunk/build_dir/host/cmake-2.8.11.2/Tests/RunCMake/include" "-DRunCMake_BINARY_DIR=/home/dogi/openwrt/trunk/build_dir/host/cmake-2.8.11.2/Tests/RunCMake/include" "-P" "/home/dogi/openwrt/trunk/build_dir/host/cmake-2.8.11.2/Tests/RunCMake/include/RunCMakeTest.cmake")
ADD_TEST(RunCMake.include_directories "/home/dogi/openwrt/trunk/build_dir/host/cmake-2.8.11.2/bin/cmake" "-DCMAKE_MODULE_PATH=/home/dogi/openwrt/trunk/build_dir/host/cmake-2.8.11.2/Tests/RunCMake" "-DRunCMake_GENERATOR=Unix Makefiles" "-DRunCMake_GENERATOR_TOOLSET=" "-DRunCMake_SOURCE_DIR=/home/dogi/openwrt/trunk/build_dir/host/cmake-2.8.11.2/Tests/RunCMake/include_directories" "-DRunCMake_BINARY_DIR=/home/dogi/openwrt/trunk/build_dir/host/cmake-2.8.11.2/Tests/RunCMake/include_directories" "-P" "/home/dogi/openwrt/trunk/build_dir/host/cmake-2.8.11.2/Tests/RunCMake/include_directories/RunCMakeTest.cmake")
ADD_TEST(RunCMake.list "/home/dogi/openwrt/trunk/build_dir/host/cmake-2.8.11.2/bin/cmake" "-DCMAKE_MODULE_PATH=/home/dogi/openwrt/trunk/build_dir/host/cmake-2.8.11.2/Tests/RunCMake" "-DRunCMake_GENERATOR=Unix Makefiles" "-DRunCMake_GENERATOR_TOOLSET=" "-DRunCMake_SOURCE_DIR=/home/dogi/openwrt/trunk/build_dir/host/cmake-2.8.11.2/Tests/RunCMake/list" "-DRunCMake_BINARY_DIR=/home/dogi/openwrt/trunk/build_dir/host/cmake-2.8.11.2/Tests/RunCMake/list" "-P" "/home/dogi/openwrt/trunk/build_dir/host/cmake-2.8.11.2/Tests/RunCMake/list/RunCMakeTest.cmake")
ADD_TEST(RunCMake.CMP0004 "/home/dogi/openwrt/trunk/build_dir/host/cmake-2.8.11.2/bin/cmake" "-DCMAKE_MODULE_PATH=/home/dogi/openwrt/trunk/build_dir/host/cmake-2.8.11.2/Tests/RunCMake" "-DRunCMake_GENERATOR=Unix Makefiles" "-DRunCMake_GENERATOR_TOOLSET=" "-DRunCMake_SOURCE_DIR=/home/dogi/openwrt/trunk/build_dir/host/cmake-2.8.11.2/Tests/RunCMake/CMP0004" "-DRunCMake_BINARY_DIR=/home/dogi/openwrt/trunk/build_dir/host/cmake-2.8.11.2/Tests/RunCMake/CMP0004" "-P" "/home/dogi/openwrt/trunk/build_dir/host/cmake-2.8.11.2/Tests/RunCMake/CMP0004/RunCMakeTest.cmake")
